const state = {
	connection: { country: 'USA', city: 'Atlanta', icon: require('../../assets/flags/united-states.png'), range: 1 },
	servers: {
		free: [
			{ country: 'USA', city: 'Atlanta', icon: require('../../assets/flags/united-states.png'), range: 1 },
			{ country: 'Canada', city: 'Toronto', icon: require('../../assets/flags/canada.png'), range: 2 },
			{ country: 'France', city: 'Paris', icon: require('../../assets/flags/france.png'), range: 1 },
			{ country: 'Germany', city: 'Frankfurt', icon: require('../../assets/flags/germany.png'), range: 2 },
		],
		premium: [
			{ country: 'USA', city: 'Chicago', icon: require('../../assets/flags/united-states.png'), range: 4 },
			{ country: 'USA', city: 'Miami', icon: require('../../assets/flags/united-states.png'), range: 3 },
			{ country: 'USA', city: 'New York', icon: require('../../assets/flags/united-states.png'), range: 4 },
			{ country: 'USA', city: 'Los Angeles', icon: require('../../assets/flags/united-states.png'), range: 4 },
			{ country: 'Canada', city: 'Halifax', icon: require('../../assets/flags/canada.png'), range: 4 },
			{ country: 'Canada', city: 'Montreal', icon: require('../../assets/flags/canada.png'), range: 4 },
			{ country: 'Canada', city: 'Vancouver', icon: require('../../assets/flags/canada.png'), range: 4 },
			{ country: 'Austria', city: 'Vienna', icon: require('../../assets/flags/austria.png'), range: 3 },
			{ country: 'Belgium', city: 'Brussels', icon: require('../../assets/flags/belgium.png'), range: 4 },
			{ country: 'Bulgaria', city: 'Sofia', icon: require('../../assets/flags/bulgaria.png'), range: 4 },
			{ country: 'Croatia', city: 'Zagreb', icon: require('../../assets/flags/croatia.png'), range: 3 },
			{ country: 'Finland', city: 'Helsinki', icon: require('../../assets/flags/finland.png'), range: 4 },
			{ country: 'France', city: 'Paris', icon: require('../../assets/flags/france.png'), range: 4 },
			{ country: 'Germany', city: 'Frankfurt', icon: require('../../assets/flags/germany.png'), range: 3 },
			{ country: 'Greece', city: 'Athens', icon: require('../../assets/flags/greece.png'), range: 4 },
			{ country: 'Hungary', city: 'Budapest', icon: require('../../assets/flags/hungary.png'), range: 4 },
			{ country: 'Israel', city: 'Ashdod', icon: require('../../assets/flags/israel.png'), range: 4 },
			{ country: 'Israel', city: 'Jerusalem', icon: require('../../assets/flags/israel.png'), range: 4 },
			{ country: 'Italy', city: 'Milan', icon: require('../../assets/flags/italy.png'), range: 4 },
			{ country: 'Italy', city: 'Rome', icon: require('../../assets/flags/italy.png'), range: 3 },
			{ country: 'Netherlands', city: 'Amsterdam', icon: require('../../assets/flags/netherlands.png'), range: 4 },
			{ country: 'Norway', city: 'Oslo', icon: require('../../assets/flags/norway.png'), range: 4 },
			{ country: 'Poland', city: 'Warsaw', icon: require('../../assets/flags/poland.png'), range: 4 },
			{ country: 'Sweden', city: 'Stockholm', icon: require('../../assets/flags/sweden.png'), range: 3 },
			{ country: 'UK', city: 'Edinburgh', icon: require('../../assets/flags/united-kingdom.png'), range: 4 },
			{ country: 'UK', city: 'London', icon: require('../../assets/flags/united-kingdom.png'), range: 4 },
			{ country: 'UK', city: 'Manchester', icon: require('../../assets/flags/united-kingdom.png'), range: 4 },
			{ country: 'India', city: 'Chennai', icon: require('../../assets/flags/india.png'), range: 4 },
			{ country: 'India', city: 'Mumbai', icon: require('../../assets/flags/india.png'), range: 3 },
			{ country: 'India', city: 'Pune', icon: require('../../assets/flags/india.png'), range: 4 },
			{ country: 'Russia', city: 'Moscow', icon: require('../../assets/flags/russia.png'), range: 4 },
			{ country: 'New Zealand', city: 'Auckland', icon: require('../../assets/flags/new-zealand.png'), range: 4 },
			{ country: 'Hong Kong', city: 'Hong Kong', icon: require('../../assets/flags/hong-kong.png'), range: 3 },
			{ country: 'Japan', city: 'Tokyo', icon: require('../../assets/flags/japan.png'), range: 4 },
			{ country: 'South Korea', city: 'Seoul', icon: require('../../assets/flags/south-korea.png'), range: 4 },
			{ country: 'Thailand', city: 'Bangkok', icon: require('../../assets/flags/thailand.png'), range: 4 },
		],
	},
};

export default state;
